export const TREATMENT_MENU = [
    {
        id: 'injeksjoner',
        title: 'Injeksjonsbehandlinger',
        subtitle: 'Filler, rynkebehandling og skinbooster',
        url: 'https://www.tmklinikken.no/behandlinger/injeksjonsbehandlinger',
        // icon: 'medkit-outline',
        image: require('@/assets/images/icons/icon_injeksjoner_final.png'),
    },
    {
        id: 'laser',
        title: 'Laserbehandlinger',
        subtitle: 'Hårfjerning, kar og pigmentering',
        url: 'https://www.tmklinikken.no/behandlinger/laserbehandlinger',
        // icon: 'flash-outline',
        image: require('@/assets/images/icons/icon_laser_final.png'),
    },
    {
        id: 'ansikt',
        title: 'Ansiktsbehandlinger',
        subtitle: 'Medisinsk hudpleie og velvære',
        url: 'https://www.tmklinikken.no/behandlinger/ansiktsbehandlinger',
        // icon: 'happy-outline',
        image: require('@/assets/images/icons/icon_ansikt_final.png'),
    },
    {
        id: 'hud',
        title: 'Hud & Peelinger',
        subtitle: 'Dermapen, kjemisk peel og mesoterapi',
        url: 'https://www.tmklinikken.no/behandlinger/peelinger',
        // icon: 'water-outline',
        image: require('@/assets/images/icons/icon_hud_final.png'),
    },
    {
        id: 'kropp',
        title: 'Kropp & Massasje',
        subtitle: 'Figurforming og massasje',
        url: 'https://www.tmklinikken.no/behandlinger/kroppsbehandling-og-massasje',
        // icon: 'accessibility-outline',
        image: require('@/assets/images/icons/icon_kropp_final.png'),
    },
    {
        id: 'vipper_bryn',
        title: 'Vipper og Bryn',
        subtitle: 'Løft, laminering og design',
        url: 'https://www.tmklinikken.no/behandlinger/vipper-og-bryn',
        // icon: 'eye-outline',
        image: require('@/assets/images/icons/icon_bryn_final.png'),
    },
    {
        id: 'tannbleking',
        title: 'Kosmetisk Tannbleking',
        subtitle: 'Skånsom og effektiv bleking',
        url: 'https://www.tmklinikken.no/behandlinger/kosmetisk-tannbleking',
        // icon: 'sunny-outline',
        image: require('@/assets/images/icons/icon_tannbleking_final.png'),
    },
    {
        id: 'lege',
        title: 'Lege & Sykepleier',
        subtitle: 'Medisinske tjenester',
        url: 'https://www.tmklinikken.no/behandlinger/lege-og-sykepleiertjenester',
        icon: 'pulse-outline',
        image: require('@/assets/images/illustrations/doctor_v2.png'),
    },
    {
        id: 'priser',
        title: 'Prisliste',
        subtitle: 'Se våre priser',
        url: 'https://tmklinikken.no/behandlinger/#priser',
        icon: 'cash-outline',
        image: require('@/assets/images/illustrations/doctor_v2.png'),
    },
    {
        id: 'bestill',
        title: 'Bestill time',
        subtitle: 'Finn en tid som passer',
        url: 'https://tmklinikken.bestille.no/OnCust2/#!/ ',
        icon: 'calendar-outline',
        image: require('@/assets/images/illustrations/doctor_v2.png'),
    }
];

export const MAIN_TABS = ['Behandlinger', 'Bestill time', 'Om oss', 'Kontakt', 'TM Klinikken'];
